# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr: none

pool:
  vmImage: 'windows-2022'

name: Solution-Pull-Request-$(Date:yyyyMMdd)-$(Rev:.rrr)

variables:
- name: BuildPackageFile
  value: Package 

steps:
# Enable long paths before doing git checkout
- powershell: |
   git config --system core.longpaths true
  displayName: 'Build and package all components.'

# Check out the source
- checkout: self

- script: echo '$(Build.SourcesDirectory)\DevOps-Pipelines\DevOps-Create-PR.ps1 -packages solution -targetEnvironment $(TargetEnvironment) -appId $(AppId) -clientSecret ***************'

# Run the Create Pull Request Script
- powershell: '$(Build.SourcesDirectory)\DevOps-Pipelines\DevOps-Create-PR.ps1 -packages solution -targetEnvironment $(TargetEnvironment) -appId $(AppId) -clientSecret $(ClientSecret)  -buildPackageFile $(BuildPackageFile)'
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  displayName: 'Dev Ops Create Solution/Data/Portals Pull Request.'
