# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include: 
      - master
      - main
  paths:
    include: 
      - Solutions/*
      - ConfigurationData/SolutionBuilds/*
      - Portals/*
      - Plugins/*
      - WebResources/*
    exclude:
      - README.md

pr: none

pool:
  vmImage: 'windows-2022'


parameters:
- name: Solution # name of the parameter; required
  type: string # data type of the parameter; required
  default: 

name: CI-Build-$(Date:yyyyMMdd)-$(Rev:.rrr)

variables:
- name: BuildPackageFile
  value: Package 

steps:
# Check out the source
- checkout: self

- template: DevOps-Pipeline-Template-Build.yml 

# Publish build artifacts
# Publish build artifacts to Azure Pipelines or a Windows file share
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.SourcesDirectory)\Build' 
    artifactName: 'Package' 
    #publishLocation: 'Container' # Options: container, filePath
    #targetPath: # Required when publishLocation == FilePath
    #parallel: false # Optional
    #parallelCount: # Optional
    #fileCopyOptions: #Optional
    #storeAsTar: false # Optional